// Shapes returned by the queries in ./queries.ts. The Studio schema
// (src/sanity/schemaTypes/) is the source of truth; these follow its projections.
import type { PortableTextBlock } from "@portabletext/react";

export interface SanityImage {
  /** Null when the image has no uploaded file. */
  url: string | null;
  alt?: string | null;
  /** Base64 blur placeholder generated by Sanity. */
  lqip?: string | null;
  dimensions?: { width: number; height: number } | null;
  /** Crop set in the Studio: how much to trim from each side, as fractions. */
  crop?: { top: number; bottom: number; left: number; right: number } | null;
  /** Focal point chosen in the Studio, as fractions of the full image's width and height. */
  hotspot?: { x: number; y: number } | null;
}

export interface CaseStudyCategory {
  slug: string;
  title: string;
}

export interface CaseStudySummary {
  slug: string;
  title: string;
  summary: string;
  category: CaseStudyCategory | null;
  location: string;
  publishedAt: string;
  featured: boolean;
  image: SanityImage | null;
}

export type CaseStudyBodyBlock =
  | PortableTextBlock
  | ({ _type: "bodyImage"; _key: string } & SanityImage)
  | {
      _type: "stats";
      _key: string;
      items: { _key: string; value: string; unit?: string; label: string }[];
    }
  | { _type: "mapLink"; _key: string; href: string };

export interface CaseStudy extends CaseStudySummary {
  deployment: string | null;
  body: CaseStudyBodyBlock[] | null;
  /** Language the body is in: the reader's, or English when it isn't translated. */
  bodyLanguage: string;
  related: CaseStudySummary[];
}

export type PolicyBodyBlock =
  | PortableTextBlock
  | {
      _type: "definitions";
      _key: string;
      items: { _key: string; term: string; description: string }[];
    }
  | { _type: "callToAction"; _key: string; text: string; href: string }
  | { _type: "contacts"; _key: string; items: { _key: string; label: string; email: string }[] };

export interface PolicySection {
  id: string;
  title: string;
  /** Language the title is in: the reader's, or English when it isn't translated. */
  titleLanguage: string;
  body: PolicyBodyBlock[];
  /** Language the section is in: the reader's, or English when it isn't translated. */
  language: string;
}

export interface LegalPage {
  lastUpdated: string;
  sections: PolicySection[];
}
