// Shapes returned by the queries in ./queries.ts. The Studio schema
// (src/sanity/schemaTypes/) is the source of truth; these follow its projections.
import type { PortableTextBlock } from "@portabletext/react";
import type { SeoPageKey } from "@/lib/seo/defaults";

export interface SanityImage {
  /** Null when the image has no uploaded file. */
  url: string | null;
  alt?: string | null;
  /** Base64 blur placeholder generated by Sanity. */
  lqip?: string | null;
  dimensions?: { width: number; height: number } | null;
  /** Crop set in the Studio: how much to trim from each side, as fractions. */
  crop?: { top: number; bottom: number; left: number; right: number } | null;
  /** Focal point chosen in the Studio, as fractions of the full image's width and height. */
  hotspot?: { x: number; y: number } | null;
}

/** A "Search and sharing" object. Empty strings and a null image mean "use the page's own". */
export interface Seo {
  title: string;
  description: string;
  image: SanityImage | null;
}

export interface CaseStudyCategory {
  slug: string;
  title: string;
}

export interface CaseStudySummary {
  slug: string;
  title: string;
  summary: string;
  category: CaseStudyCategory | null;
  location: string;
  publishedAt: string;
  featured: boolean;
  image: SanityImage | null;
}

export type CaseStudyBodyBlock =
  | PortableTextBlock
  | ({ _type: "bodyImage"; _key: string } & SanityImage)
  | {
      _type: "stats";
      _key: string;
      items: { _key: string; value: string; unit?: string; label: string }[];
    }
  | { _type: "mapLink"; _key: string; href: string };

export interface CaseStudy extends CaseStudySummary {
  deployment: string | null;
  body: CaseStudyBodyBlock[] | null;
  /** Language the body is in: the reader's, or English when it isn't translated. */
  bodyLanguage: string;
  /** When the document last changed (Sanity's `_updatedAt`). */
  updatedAt: string;
  seo: Seo;
  related: CaseStudySummary[];
}

export type PolicyBodyBlock =
  | PortableTextBlock
  | {
      _type: "definitions";
      _key: string;
      items: { _key: string; term: string; description: string }[];
    }
  | { _type: "callToAction"; _key: string; text: string; href: string }
  | { _type: "contacts"; _key: string; items: { _key: string; label: string; email: string }[] };

export interface PolicySection {
  id: string;
  /** Null for an untitled (introductory) section. */
  title: string | null;
  /** Language the title is in: the reader's, or English when it isn't translated. */
  titleLanguage: string;
  body: PolicyBodyBlock[];
  /** Language the section is in: the reader's, or English when it isn't translated. */
  language: string;
}

export interface PageHero {
  eyebrow: string;
  title: string;
  description: string;
}

export interface LegalPage {
  hero: PageHero;
  seo: Seo;
  /** Only the privacy policy shows one. */
  lastUpdated: string | null;
  /** When the document last changed (Sanity's `_updatedAt`). */
  updatedAt: string;
  sections: PolicySection[];
}

export interface FaqItem {
  _key: string;
  question: string;
  answer: string;
}

/** The home page sections the about page shows too. */
export interface SharedHomeSections {
  stats: { _key: string; value: string; label: string }[];
  howItWorks: { heading: string; description: string; steps: { _key: string; title: string; description: string }[] };
  faqsLabel: string;
  impact: { title: string; description: string };
  banner: { text: string; cta: string };
}

export interface HomePageContent extends SharedHomeSections {
  hero: { titleLine1: string; titleLine2: string; description: string; primaryCta: string; secondaryCta: string };
  explore: { heading: string; description: string };
  /** `title` may hold line breaks. */
  speakNaturally: { title: string; description: string; cta: string };
  insights: {
    label: string;
    heading: string;
    description: string;
    cta: string;
    readStory: string;
    sampleTitles: { _key: string; title: string }[];
  };
  faqs: { label: string; heading: string; description: string; items: FaqItem[] };
  seo: Seo;
}

export interface AboutPageContent {
  hero: { title: string; description: string; objective: string };
  /** `description` contains {count}, the number of languages. */
  languages: { heading: string; description: string };
  /** `title` may hold line breaks. */
  safety: { title: string; description: string; items: FaqItem[] };
  cta: { title: string; description: string; primaryCta: string; secondaryCta: string };
  seo: Seo;
  /** From the home page document. */
  home: SharedHomeSections;
}

/** The `seoSettings` document: the site's description and share image, and each code-built page's search text. */
export interface SeoSettings {
  description: string;
  image: SanityImage | null;
  pages: Record<SeoPageKey, Seo>;
}

export interface SitemapContent {
  caseStudies: { slug: string; updatedAt: string }[];
  pages: { _id: string; updatedAt: string }[];
}

/** What llms-full.txt is built from, in English. */
export interface LlmsContent {
  home: HomePageContent | null;
  about: Pick<AboutPageContent, "hero" | "languages" | "safety" | "seo"> | null;
  caseStudies: (CaseStudySummary & { deployment: string | null; body: CaseStudyBodyBlock[] | null })[];
  policies: {
    _id: string;
    hero: PageHero;
    seo: Seo;
    sections: { id: string; title: string | null; body: PolicyBodyBlock[] | null }[];
  }[];
}
