// Sample data that follows the structure from your provided example
// This can be used across different dashboard components

export const sampleDashboardData = [
  {
    id: 1,
    header: "Security Incident Report",
    type: "Incident",
    status: "In Process",
    target: "High",
    limit: "24h",
    reviewer: "John Smith",
  },
  {
    id: 2,
    header: "Weekly Safety Audit",
    type: "Audit",
    status: "Done",
    target: "Medium",
    limit: "7d",
    reviewer: "Jane Doe",
  },
  {
    id: 3,
    header: "Equipment Inspection",
    type: "Inspection",
    status: "Done",
    target: "Low",
    limit: "30d",
    reviewer: "Mike Johnson",
  },
  {
    id: 4,
    header: "Access Control Review",
    type: "Review",
    status: "Done",
    target: "High",
    limit: "24h",
    reviewer: "Sarah Wilson",
  },
  {
    id: 5,
    header: "Emergency Response Drill",
    type: "Drill",
    status: "In Process",
    target: "Medium",
    limit: "7d",
    reviewer: "David Brown",
  },
  {
    id: 6,
    header: "Visitor Registration Check",
    type: "Check",
    status: "In Process",
    target: "Low",
    limit: "1h",
    reviewer: "Emily Davis",
  },
  {
    id: 7,
    header: "CCTV System Monitoring",
    type: "Monitoring",
    status: "In Process",
    target: "High",
    limit: "24h",
    reviewer: "Alex Miller",
  },
  {
    id: 8,
    header: "Perimeter Security Check",
    type: "Check",
    status: "Done",
    target: "Medium",
    limit: "12h",
    reviewer: "Lisa Garcia",
  },
  {
    id: 9,
    header: "Fire Safety Inspection",
    type: "Inspection",
    status: "Done",
    target: "High",
    limit: "24h",
    reviewer: "Robert Taylor",
  },
  {
    id: 10,
    header: "IT Security Assessment",
    type: "Assessment",
    status: "Done",
    target: "High",
    limit: "72h",
    reviewer: "Jennifer White",
  },
];

export const organizationStats = {
  superAdmin: {
    totalOrganizations: 28,
    totalAdmins: 156,
    totalWatchers: 847,
    totalIncidents: 1247,
    totalReports: 394,
    totalForms: 67,
    activeUsers: 892,
    systemUptime: "99.9%",
  },
  admin: {
    totalWatchers: 23,
    totalIncidents: 89,
    totalReports: 15,
    totalForms: 8,
    activeUsers: 24,
    responseRate: "97%",
    completionRate: "94%",
  },
  watcher: {
    myReports: 12,
    myIncidents: 7,
    availableForms: 8,
    completedTasks: 47,
    pendingTasks: 3,
    completionRate: "95%",
  },
};

export const chartData = {
  organizationTypes: [
    { name: "NGOs", value: 12, color: "bg-blue-500" },
    { name: "Corporate", value: 8, color: "bg-green-500" },
    { name: "Government", value: 5, color: "bg-yellow-500" },
    { name: "Academic", value: 3, color: "bg-purple-500" },
  ],
  incidentTypes: [
    { name: "Security", value: 15, color: "bg-red-500" },
    { name: "Technical", value: 8, color: "bg-blue-500" },
    { name: "Safety", value: 12, color: "bg-orange-500" },
    { name: "Access", value: 6, color: "bg-green-500" },
    { name: "Other", value: 4, color: "bg-gray-500" },
  ],
  weeklyActivity: [
    { period: "Mon", value: 4 },
    { period: "Tue", value: 3 },
    { period: "Wed", value: 5 },
    { period: "Thu", value: 2 },
    { period: "Fri", value: 6 },
    { period: "Sat", value: 1 },
    { period: "Sun", value: 2 },
  ],
  monthlyTrend: [
    { period: "Week 1", value: 145 },
    { period: "Week 2", value: 167 },
    { period: "Week 3", value: 134 },
    { period: "Week 4", value: 189 },
    { period: "Week 5", value: 201 },
    { period: "Week 6", value: 178 },
    { period: "Week 7", value: 234 },
  ],
};
